---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "server.name" . }}{{ .Values.server_num}}
spec:
  selector:
    app: {{ template "server.fullname" . }}
  clusterIP: None
  ports:
  - name: mp # Actually, no port is needed.
    port: 34197
    targetPort: 34197
  - name: discovery # Actually, no port is needed.
    port: 34196
    targetPort: 34196