image: warsow
imageTag: latest
imagePrefix: dockerreg.lanadmins.net/
imageSecret: dockerreglanadminsnet

resources:
  requests:
    memory: 1000Mi
    cpu: 750m

server:
  fullname: Warsow Comp Server
  description: Warsow Comp Server
  lan: 1
  